export const COMPANY_REQUEST = "COMPANY_REQUEST";
export const COMPANY_RESPONSE = "COMPANY_SUCCESS";
export const COMPANY_FAILURE = "COMPANY_FAILURE";
export const COMPANY_SET_DATA = "COMPANY_SET_DATA";
export const COMPANY_RESET_DATA = "COMPANY_RESET_DATA";
